<?php
/**
 * Charj.in — Vehicle Seeder
 * Seeds 20 popular Indian EVs with images, specs, and pricing.
 * Run once: http://localhost/Charj/public/seed_vehicles.php
 */

$pdo = new PDO('mysql:host=localhost;dbname=u504377054_charj;charset=utf8mb4', 'root', '');
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

// Get brand IDs
$brandMap = [];
foreach ($pdo->query("SELECT id, slug FROM brands")->fetchAll(PDO::FETCH_ASSOC) as $b) {
    $brandMap[$b['slug']] = $b['id'];
}

$vehicles = [

    // ── OLA ELECTRIC ──────────────────────────────────────────────
    [
        'brand_slug'         => 'ola-electric',
        'name'               => 'Ola S1 Pro',
        'slug'               => 'ola-s1-pro',
        'segment'            => '2_wheeler',
        'body_type'          => 'Scooter',
        'short_description'  => 'India\'s best-selling electric scooter with 195km real-world range and MoveOS 5.',
        'starting_price'     => 134999,
        'max_price'          => 154999,
        'ex_showroom_price'  => 134999,
        'real_world_range'   => 170,
        'claimed_range'      => 195,
        'top_speed'          => 120,
        'battery_capacity'   => 4.0,
        'battery_type'       => 'Lithium-Ion NMC',
        'motor_power'        => 8500,
        'motor_torque'       => 58,
        'charging_time_fast' => 18,
        'charging_time_normal'=> 6.5,
        'fast_charging'      => 1,
        'warranty_years'     => 3,
        'battery_warranty_years' => 3,
        'seating_capacity'   => 2,
        'colors_available'   => 'Jet Black, Pearl White, Coral Bliss, Porcelain White, Slate Grey, Stellar Blue',
        'expert_rating'      => 4.3,
        'featured'           => 1,
        'status'             => 'published',
        'image_url'          => 'https://www.91wheels.com/assets/images/models/4617/ola-electric-s1-pro-gen-2.jpg',
        'pros_json'          => json_encode(['Best-in-class range','Fast OTA updates via MoveOS','Hyper charging support','Large boot space']),
        'cons_json'          => json_encode(['Software glitches reported','Service center availability','Resale value uncertainty']),
    ],
    [
        'brand_slug'         => 'ola-electric',
        'name'               => 'Ola S1 Air',
        'slug'               => 'ola-s1-air',
        'segment'            => '2_wheeler',
        'body_type'          => 'Scooter',
        'short_description'  => 'Affordable entry into Ola\'s ecosystem with 101km claimed range.',
        'starting_price'     => 99999,
        'max_price'          => 104999,
        'ex_showroom_price'  => 99999,
        'real_world_range'   => 85,
        'claimed_range'      => 101,
        'top_speed'          => 85,
        'battery_capacity'   => 2.5,
        'battery_type'       => 'Lithium-Ion',
        'motor_power'        => 6000,
        'motor_torque'       => 30,
        'charging_time_normal'=> 4.5,
        'fast_charging'      => 0,
        'warranty_years'     => 3,
        'battery_warranty_years' => 3,
        'seating_capacity'   => 2,
        'colors_available'   => 'Jet Black, Porcelain White, Midnight Blue',
        'expert_rating'      => 3.9,
        'featured'           => 0,
        'status'             => 'published',
        'image_url'          => 'https://www.91wheels.com/assets/images/models/4618/ola-electric-s1-air.jpg',
        'pros_json'          => json_encode(['Budget-friendly','MoveOS features','Decent range for city']),
        'cons_json'          => json_encode(['No fast charging','Lower top speed','Smaller boot']),
    ],

    // ── ATHER ENERGY ──────────────────────────────────────────────
    [
        'brand_slug'         => 'ather-energy',
        'name'               => 'Ather 450X',
        'slug'               => 'ather-450x',
        'segment'            => '2_wheeler',
        'body_type'          => 'Scooter',
        'short_description'  => 'The performance scooter with 146km IDC range, AtherStack 6.0, and fast charging.',
        'starting_price'     => 145990,
        'max_price'          => 164990,
        'ex_showroom_price'  => 145990,
        'real_world_range'   => 105,
        'claimed_range'      => 146,
        'top_speed'          => 90,
        'battery_capacity'   => 3.7,
        'battery_type'       => 'Lithium-Ion NMC',
        'motor_power'        => 6200,
        'motor_torque'       => 26,
        'charging_time_fast' => 15,
        'charging_time_normal'=> 5.5,
        'fast_charging'      => 1,
        'warranty_years'     => 3,
        'battery_warranty_years' => 3,
        'seating_capacity'   => 2,
        'colors_available'   => 'Space Grey, Classic Black, Mint, White',
        'expert_rating'      => 4.5,
        'featured'           => 1,
        'status'             => 'published',
        'image_url'          => 'https://www.91wheels.com/assets/images/models/2048/ather-450x.jpg',
        'pros_json'          => json_encode(['Best-in-class handling','AtherGrid fast charging network','Regular OTA updates','Premium build quality']),
        'cons_json'          => json_encode(['Premium pricing','Limited service centers outside metro','Boot space average']),
    ],
    [
        'brand_slug'         => 'ather-energy',
        'name'               => 'Ather Rizta',
        'slug'               => 'ather-rizta',
        'segment'            => '2_wheeler',
        'body_type'          => 'Scooter',
        'short_description'  => 'Family scooter with 160km range, large storage and a comfortable ride.',
        'starting_price'     => 109999,
        'max_price'          => 154999,
        'ex_showroom_price'  => 109999,
        'real_world_range'   => 123,
        'claimed_range'      => 160,
        'top_speed'          => 80,
        'battery_capacity'   => 3.7,
        'battery_type'       => 'Lithium-Ion NMC',
        'motor_power'        => 5400,
        'motor_torque'       => 22,
        'charging_time_fast' => 15,
        'charging_time_normal'=> 5.5,
        'fast_charging'      => 1,
        'warranty_years'     => 3,
        'battery_warranty_years' => 3,
        'seating_capacity'   => 2,
        'colors_available'   => 'Deep Blue, Sunset Red, Ivory White, Midnight Black',
        'expert_rating'      => 4.2,
        'featured'           => 1,
        'status'             => 'published',
        'image_url'          => 'https://www.91wheels.com/assets/images/models/5178/ather-rizta.jpg',
        'pros_json'          => json_encode(['Family-friendly design','Large 43L storage','Comfortable for two','Fast charging']),
        'cons_json'          => json_encode(['Slightly lower performance','Heavier than 450X']),
    ],

    // ── TVS MOTOR ──────────────────────────────────────────────
    [
        'brand_slug'         => 'tvs-motor',
        'name'               => 'TVS iQube S',
        'slug'               => 'tvs-iqube-s',
        'segment'            => '2_wheeler',
        'body_type'          => 'Scooter',
        'short_description'  => 'Smart connected scooter with 100km real-world range and navigation.',
        'starting_price'     => 94999,
        'max_price'          => 146344,
        'ex_showroom_price'  => 94999,
        'real_world_range'   => 75,
        'claimed_range'      => 100,
        'top_speed'          => 78,
        'battery_capacity'   => 3.4,
        'battery_type'       => 'Lithium-Ion',
        'motor_power'        => 4400,
        'motor_torque'       => 140,
        'charging_time_normal'=> 5,
        'fast_charging'      => 0,
        'warranty_years'     => 3,
        'battery_warranty_years' => 3,
        'seating_capacity'   => 2,
        'colors_available'   => 'Titanium Grey, Breeze Blue, Mint Green, Red, Black',
        'expert_rating'      => 4.1,
        'featured'           => 1,
        'status'             => 'published',
        'image_url'          => 'https://www.91wheels.com/assets/images/models/3234/tvs-iqube.jpg',
        'pros_json'          => json_encode(['TVS reliability','SmartXonnect technology','Good dealer network','Multiple variants']),
        'cons_json'          => json_encode(['No fast charging on base variant','Average range','Bulky']),
    ],

    // ── TATA MOTORS ──────────────────────────────────────────────
    [
        'brand_slug'         => 'tata-motors',
        'name'               => 'Tata Nexon EV',
        'slug'               => 'tata-nexon-ev',
        'segment'            => '4_wheeler',
        'body_type'          => 'SUV',
        'short_description'  => 'India\'s best-selling electric SUV with 465km range, Ziptron technology and 5-star safety.',
        'starting_price'     => 1399900,
        'max_price'          => 1899900,
        'ex_showroom_price'  => 1399900,
        'real_world_range'   => 320,
        'claimed_range'      => 465,
        'top_speed'          => 150,
        'acceleration_0_100' => 8.9,
        'battery_capacity'   => 40.5,
        'battery_type'       => 'Lithium-Ion NMC',
        'motor_power'        => 143,
        'motor_torque'       => 215,
        'charging_time_fast' => 56,
        'charging_time_normal'=> 8.5,
        'fast_charging'      => 1,
        'warranty_years'     => 3,
        'battery_warranty_years' => 8,
        'battery_warranty_km'=> 160000,
        'seating_capacity'   => 5,
        'boot_space'         => 350,
        'ground_clearance'   => 190,
        'colors_available'   => 'Intensi-Teal, Pristine White, Daytona Grey, Flame Red, Fearless Purple',
        'expert_rating'      => 4.4,
        'featured'           => 1,
        'status'             => 'published',
        'image_url'          => 'https://www.91wheels.com/assets/images/models/3032/tata-nexon-ev.jpg',
        'pros_json'          => json_encode(['Best safety ratings in India','Ziptron technology proven','Excellent build quality','Extensive service network','8yr battery warranty']),
        'cons_json'          => json_encode(['Charging time could be better','Interior quality vs price','Limited rear legroom']),
    ],
    [
        'brand_slug'         => 'tata-motors',
        'name'               => 'Tata Punch EV',
        'slug'               => 'tata-punch-ev',
        'segment'            => '4_wheeler',
        'body_type'          => 'Micro SUV',
        'short_description'  => 'Compact electric SUV with 421km range, ideal for city and highway.',
        'starting_price'     => 999900,
        'max_price'          => 1399900,
        'ex_showroom_price'  => 999900,
        'real_world_range'   => 280,
        'claimed_range'      => 421,
        'top_speed'          => 140,
        'acceleration_0_100' => 9.5,
        'battery_capacity'   => 35,
        'battery_type'       => 'Lithium-Ion',
        'motor_power'        => 122,
        'motor_torque'       => 190,
        'charging_time_fast' => 56,
        'charging_time_normal'=> 9.4,
        'fast_charging'      => 1,
        'warranty_years'     => 3,
        'battery_warranty_years' => 8,
        'seating_capacity'   => 5,
        'boot_space'         => 366,
        'ground_clearance'   => 187,
        'colors_available'   => 'Pristine White, Daytona Grey, Seaweed Green, Galactic Sapphire',
        'expert_rating'      => 4.3,
        'featured'           => 1,
        'status'             => 'published',
        'image_url'          => 'https://www.91wheels.com/assets/images/models/5013/tata-punch-ev.jpg',
        'pros_json'          => json_encode(['Affordable entry EV car','Excellent boot space','5-star safety','V2L capability']),
        'cons_json'          => json_encode(['Small cabin for 5 adults','Rear AC vents missing base','Charging speed average']),
    ],
    [
        'brand_slug'         => 'tata-motors',
        'name'               => 'Tata Tiago EV',
        'slug'               => 'tata-tiago-ev',
        'segment'            => '4_wheeler',
        'body_type'          => 'Hatchback',
        'short_description'  => 'India\'s most affordable electric car with 315km range and modern features.',
        'starting_price'     => 799900,
        'max_price'          => 1099900,
        'ex_showroom_price'  => 799900,
        'real_world_range'   => 220,
        'claimed_range'      => 315,
        'top_speed'          => 130,
        'battery_capacity'   => 24,
        'battery_type'       => 'Lithium-Ion',
        'motor_power'        => 55,
        'motor_torque'       => 114,
        'charging_time_fast' => 58,
        'charging_time_normal'=> 8.7,
        'fast_charging'      => 1,
        'warranty_years'     => 3,
        'battery_warranty_years' => 8,
        'seating_capacity'   => 5,
        'boot_space'         => 242,
        'ground_clearance'   => 165,
        'colors_available'   => 'Teal Blue, Midnight Black, Pristine White, Daytona Grey',
        'expert_rating'      => 4.1,
        'featured'           => 1,
        'status'             => 'published',
        'image_url'          => 'https://www.91wheels.com/assets/images/models/4556/tata-tiago-ev.jpg',
        'pros_json'          => json_encode(['Most affordable 4W EV','Peppy city driving','5-star safety','Tata reliability']),
        'cons_json'          => json_encode(['Less range vs rivals','Small boot','Rear comfort average']),
    ],

    // ── MG MOTOR ──────────────────────────────────────────────
    [
        'brand_slug'         => 'mg-motor',
        'name'               => 'MG Windsor EV',
        'slug'               => 'mg-windsor-ev',
        'segment'            => '4_wheeler',
        'body_type'          => 'SUV',
        'short_description'  => 'Crossover EV with 331km range, BaaS model and premium interiors.',
        'starting_price'     => 1349800,
        'max_price'          => 1599800,
        'ex_showroom_price'  => 1349800,
        'real_world_range'   => 230,
        'claimed_range'      => 331,
        'top_speed'          => 135,
        'acceleration_0_100' => 8.5,
        'battery_capacity'   => 38,
        'battery_type'       => 'Lithium Iron Phosphate',
        'motor_power'        => 134,
        'motor_torque'       => 200,
        'charging_time_fast' => 55,
        'charging_time_normal'=> 6.5,
        'fast_charging'      => 1,
        'warranty_years'     => 5,
        'battery_warranty_years' => 8,
        'seating_capacity'   => 5,
        'boot_space'         => 604,
        'ground_clearance'   => 174,
        'colors_available'   => 'Starburst Black, Pearl White, Starry Black, Turquoise Green',
        'expert_rating'      => 4.2,
        'featured'           => 1,
        'status'             => 'published',
        'image_url'          => 'https://www.91wheels.com/assets/images/models/5107/mg-windsor-ev.jpg',
        'pros_json'          => json_encode(['Largest boot space in class','Comfortable rear seat reclining','BaaS lowers upfront cost','Premium ambient lighting']),
        'cons_json'          => json_encode(['Range below some rivals','Lower ground clearance','Charging network smaller than Tata']),
    ],
    [
        'brand_slug'         => 'mg-motor',
        'name'               => 'MG ZS EV',
        'slug'               => 'mg-zs-ev',
        'segment'            => '4_wheeler',
        'body_type'          => 'SUV',
        'short_description'  => 'Spacious mid-size electric SUV with 461km range and connected car technology.',
        'starting_price'     => 1898800,
        'max_price'          => 2299800,
        'ex_showroom_price'  => 1898800,
        'real_world_range'   => 310,
        'claimed_range'      => 461,
        'top_speed'          => 175,
        'acceleration_0_100' => 8.5,
        'battery_capacity'   => 50.3,
        'battery_type'       => 'NMC Lithium-Ion',
        'motor_power'        => 176,
        'motor_torque'       => 280,
        'charging_time_fast' => 40,
        'charging_time_normal'=> 8.5,
        'fast_charging'      => 1,
        'warranty_years'     => 5,
        'battery_warranty_years' => 8,
        'seating_capacity'   => 5,
        'boot_space'         => 448,
        'ground_clearance'   => 177,
        'colors_available'   => 'Diamond Red, Starry Black, Polar White, Essex Grey',
        'expert_rating'      => 4.3,
        'featured'           => 0,
        'status'             => 'published',
        'image_url'          => 'https://www.91wheels.com/assets/images/models/2198/mg-zs-ev.jpg',
        'pros_json'          => json_encode(['461km claimed range','Premium cabin quality','Large panoramic sunroof','Level 2 ADAS']),
        'cons_json'          => json_encode(['Premium pricing','Heavier than rivals','Charging costs higher']),
    ],

    // ── HYUNDAI ──────────────────────────────────────────────
    [
        'brand_slug'         => 'hyundai',
        'name'               => 'Hyundai Creta Electric',
        'slug'               => 'hyundai-creta-electric',
        'segment'            => '4_wheeler',
        'body_type'          => 'SUV',
        'short_description'  => 'Electric version of India\'s favourite SUV with 473km range and 16.4-inch screen.',
        'starting_price'     => 1789000,
        'max_price'          => 2349000,
        'ex_showroom_price'  => 1789000,
        'real_world_range'   => 340,
        'claimed_range'      => 473,
        'top_speed'          => 165,
        'acceleration_0_100' => 7.9,
        'battery_capacity'   => 51.4,
        'battery_type'       => 'Lithium-Ion NCM',
        'motor_power'        => 171,
        'motor_torque'       => 255,
        'charging_time_fast' => 48,
        'charging_time_normal'=> 10.2,
        'fast_charging'      => 1,
        'warranty_years'     => 3,
        'battery_warranty_years' => 8,
        'battery_warranty_km'=> 160000,
        'seating_capacity'   => 5,
        'boot_space'         => 433,
        'ground_clearance'   => 190,
        'colors_available'   => 'Atlas White, Abyss Black, Ocean Blue, Stargazing Blue, Robust Emerald',
        'expert_rating'      => 4.6,
        'featured'           => 1,
        'status'             => 'published',
        'image_url'          => 'https://www.91wheels.com/assets/images/models/5045/hyundai-creta-electric.jpg',
        'pros_json'          => json_encode(['Best-in-class 16.4" screen','473km ARAI range','V2L & V2V capable','Premium Bose sound','5 drive modes']),
        'cons_json'          => json_encode(['Higher price than Nexon EV','Sunroof not on base','AC charging slow on base']),
    ],

    // ── MAHINDRA ──────────────────────────────────────────────
    [
        'brand_slug'         => 'mahindra',
        'name'               => 'Mahindra BE 6',
        'slug'               => 'mahindra-be-6',
        'segment'            => '4_wheeler',
        'body_type'          => 'Coupe SUV',
        'short_description'  => 'Mahindra\'s flagship BE series electric coupe-SUV built on INGLO platform.',
        'starting_price'     => 1889000,
        'max_price'          => 2649000,
        'ex_showroom_price'  => 1889000,
        'real_world_range'   => 420,
        'claimed_range'      => 683,
        'top_speed'          => 210,
        'acceleration_0_100' => 6.7,
        'battery_capacity'   => 79,
        'battery_type'       => 'Lithium-Ion NMC',
        'motor_power'        => 228,
        'motor_torque'       => 380,
        'charging_time_fast' => 20,
        'charging_time_normal'=> 16.5,
        'fast_charging'      => 1,
        'warranty_years'     => 3,
        'battery_warranty_years' => 8,
        'seating_capacity'   => 5,
        'boot_space'         => 455,
        'ground_clearance'   => 207,
        'colors_available'   => 'Deep Forest, Everest White, Tectonic Blue, Nebula Black',
        'expert_rating'      => 4.5,
        'featured'           => 1,
        'status'             => 'published',
        'image_url'          => 'https://www.91wheels.com/assets/images/models/5245/mahindra-be-6.jpg',
        'pros_json'          => json_encode(['683km ARAI range','210 kmph top speed','INGLO skateboard platform','Fast 175kW DC charging','Dual-pane panoramic roof']),
        'cons_json'          => json_encode(['Premium pricing','Less practical 5-seat packaging','Limited test drives currently']),
    ],
    [
        'brand_slug'         => 'mahindra',
        'name'               => 'Mahindra XEV 9e',
        'slug'               => 'mahindra-xev-9e',
        'segment'            => '4_wheeler',
        'body_type'          => 'SUV',
        'short_description'  => 'Flagship 7-seater electric SUV on INGLO platform with 656km range.',
        'starting_price'     => 2149000,
        'max_price'          => 3049000,
        'ex_showroom_price'  => 2149000,
        'real_world_range'   => 450,
        'claimed_range'      => 656,
        'top_speed'          => 200,
        'acceleration_0_100' => 5.9,
        'battery_capacity'   => 79,
        'battery_type'       => 'Lithium-Ion NMC',
        'motor_power'        => 285,
        'motor_torque'       => 380,
        'charging_time_fast' => 20,
        'charging_time_normal'=> 16.5,
        'fast_charging'      => 1,
        'warranty_years'     => 3,
        'battery_warranty_years' => 8,
        'seating_capacity'   => 5,
        'boot_space'         => 663,
        'ground_clearance'   => 207,
        'colors_available'   => 'Desert Mist, Beryl Blue, Firespark Orange, Midnight Black',
        'expert_rating'      => 4.6,
        'featured'           => 1,
        'status'             => 'published',
        'image_url'          => 'https://www.91wheels.com/assets/images/models/5246/mahindra-xev-9e.jpg',
        'pros_json'          => json_encode(['Tri-screen 12.3" displays','0-60 in 3.7s AWD','663L boot space','Aircraft-inspired interiors']),
        'cons_json'          => json_encode(['Top variants expensive','Charging infrastructure still growing','Waiting period expected']),
    ],

    // ── REVOLT MOTORS ──────────────────────────────────────────────
    [
        'brand_slug'         => 'revolt-motors',
        'name'               => 'Revolt RV400',
        'slug'               => 'revolt-rv400',
        'segment'            => '2_wheeler',
        'body_type'          => 'Motorcycle',
        'short_description'  => 'India\'s first AI-enabled electric motorcycle with swappable battery.',
        'starting_price'     => 134999,
        'max_price'          => 144999,
        'ex_showroom_price'  => 134999,
        'real_world_range'   => 130,
        'claimed_range'      => 150,
        'top_speed'          => 85,
        'battery_capacity'   => 3.24,
        'battery_type'       => 'Lithium-Ion',
        'motor_power'        => 3000,
        'motor_torque'       => 170,
        'charging_time_normal'=> 4.5,
        'fast_charging'      => 0,
        'warranty_years'     => 3,
        'battery_warranty_years' => 3,
        'seating_capacity'   => 2,
        'colors_available'   => 'Matte Black, Red, Black',
        'expert_rating'      => 4.0,
        'featured'           => 0,
        'status'             => 'published',
        'image_url'          => 'https://www.91wheels.com/assets/images/models/2337/revolt-rv400.jpg',
        'pros_json'          => json_encode(['Motorcycle form factor','AI-enabled with custom sounds','Swappable battery option','My Revolt app']),
        'cons_json'          => json_encode(['No fast charging','Heavier than petrol bikes','Limited dealer network']),
    ],

    // ── BAJAJ AUTO ──────────────────────────────────────────────
    [
        'brand_slug'         => 'bajaj-auto',
        'name'               => 'Bajaj Chetak Premium',
        'slug'               => 'bajaj-chetak-premium',
        'segment'            => '2_wheeler',
        'body_type'          => 'Scooter',
        'short_description'  => 'Retro-modern electric scooter with 127km range and premium metal body.',
        'starting_price'     => 119998,
        'max_price'          => 130998,
        'ex_showroom_price'  => 119998,
        'real_world_range'   => 108,
        'claimed_range'      => 127,
        'top_speed'          => 73,
        'battery_capacity'   => 3.0,
        'battery_type'       => 'Lithium-Ion NMC',
        'motor_power'        => 4200,
        'motor_torque'       => 16,
        'charging_time_normal'=> 5,
        'fast_charging'      => 0,
        'warranty_years'     => 3,
        'battery_warranty_years' => 3,
        'seating_capacity'   => 2,
        'colors_available'   => 'Bronzio, Hazel Dew, Indigo Metallic, Celadon Green, Matte Black',
        'expert_rating'      => 4.0,
        'featured'           => 0,
        'status'             => 'published',
        'image_url'          => 'https://www.91wheels.com/assets/images/models/2404/bajaj-chetak.jpg',
        'pros_json'          => json_encode(['All-metal premium body','Bajaj reliability','Good resale value','Clean retro design']),
        'cons_json'          => json_encode(['No fast charging','Lower top speed','Boot space small']),
    ],

    // ── HERO ELECTRIC ──────────────────────────────────────────────
    [
        'brand_slug'         => 'hero-electric',
        'name'               => 'Hero Vida V1 Pro',
        'slug'               => 'hero-vida-v1-pro',
        'segment'            => '2_wheeler',
        'body_type'          => 'Scooter',
        'short_description'  => 'Hero MotoCorp\'s electric scooter with 165km range and fast charging.',
        'starting_price'     => 128000,
        'max_price'          => 138000,
        'ex_showroom_price'  => 128000,
        'real_world_range'   => 120,
        'claimed_range'      => 165,
        'top_speed'          => 80,
        'battery_capacity'   => 3.94,
        'battery_type'       => 'Lithium-Ion',
        'motor_power'        => 6000,
        'motor_torque'       => 25,
        'charging_time_fast' => 45,
        'charging_time_normal'=> 5.5,
        'fast_charging'      => 1,
        'warranty_years'     => 3,
        'battery_warranty_years' => 3,
        'seating_capacity'   => 2,
        'colors_available'   => 'Matte Teal, Matte Steel, Racing Red, Matte Black',
        'expert_rating'      => 3.9,
        'featured'           => 0,
        'status'             => 'published',
        'image_url'          => 'https://www.91wheels.com/assets/images/models/4419/hero-vida-v1.jpg',
        'pros_json'          => json_encode(['Large Hero dealer network','Swappable + fixed battery option','Connected features','FAME-II eligible']),
        'cons_json'          => json_encode(['Brand new EV division','Build quality mixed reviews','App needs improvement']),
    ],

    // ── AMPERE ──────────────────────────────────────────────
    [
        'brand_slug'         => 'ampere',
        'name'               => 'Ampere Nexus',
        'slug'               => 'ampere-nexus',
        'segment'            => '2_wheeler',
        'body_type'          => 'Scooter',
        'short_description'  => 'Greaves-owned Ampere\'s flagship with 136km range and full LED lighting.',
        'starting_price'     => 109900,
        'max_price'          => 124900,
        'ex_showroom_price'  => 109900,
        'real_world_range'   => 100,
        'claimed_range'      => 136,
        'top_speed'          => 75,
        'battery_capacity'   => 3.7,
        'battery_type'       => 'Lithium-Ion',
        'motor_power'        => 4800,
        'motor_torque'       => 90,
        'charging_time_normal'=> 6,
        'fast_charging'      => 0,
        'warranty_years'     => 3,
        'battery_warranty_years' => 3,
        'seating_capacity'   => 2,
        'colors_available'   => 'Majestic Bronze, Aura Blue, Black, White',
        'expert_rating'      => 3.8,
        'featured'           => 0,
        'status'             => 'published',
        'image_url'          => 'https://www.91wheels.com/assets/images/models/5012/ampere-nexus.jpg',
        'pros_json'          => json_encode(['Value for money','Good build quality','Greaves network support','Connected features']),
        'cons_json'          => json_encode(['No fast charging','Lower brand recognition','App buggy']),
    ],

];

$inserted = 0;
$skipped  = 0;
$errors   = [];

foreach ($vehicles as $v) {
    $brandSlug = $v['brand_slug'];
    unset($v['brand_slug']);

    if (!isset($brandMap[$brandSlug])) {
        $errors[] = "Brand not found: $brandSlug — run seed_brands.php first";
        continue;
    }
    $v['brand_id'] = $brandMap[$brandSlug];

    // Check if already exists
    $exists = $pdo->prepare("SELECT id FROM vehicles WHERE slug = ?");
    $exists->execute([$v['slug']]);
    if ($exists->fetch()) {
        $skipped++;
        continue;
    }

    $cols = implode(',', array_keys($v));
    $placeholders = implode(',', array_fill(0, count($v), '?'));

    try {
        $stmt = $pdo->prepare("INSERT INTO vehicles ($cols) VALUES ($placeholders)");
        $stmt->execute(array_values($v));
        $inserted++;
    } catch (PDOException $e) {
        $errors[] = "Error inserting {$v['name']}: " . $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Vehicle Seeder — Charj.in</title>
<style>
  body { font-family: sans-serif; max-width: 700px; margin: 40px auto; background: #f9f9f9; }
  .card { background: white; border: 1px solid #e5e7eb; padding: 2rem; }
  h1 { font-size: 1.4rem; color: #1B1C25; margin: 0 0 1rem; }
  .stat { font-size: 2.5rem; font-weight: 700; color: #006044; }
  .err { color: #dc2626; background: #fef2f2; border: 1px solid #fca5a5; padding: .75rem; margin-top: .5rem; font-size: .85rem; }
  a { color: #006044; font-weight: 600; }
</style>
</head>
<body>
<div class="card">
  <h1>Charj.in — Vehicle Seeder</h1>
  <p><span class="stat"><?= $inserted ?></span> vehicles inserted</p>
  <p><?= $skipped ?> already existed (skipped)</p>
  <?php foreach ($errors as $err): ?>
  <div class="err"><?= htmlspecialchars($err) ?></div>
  <?php endforeach; ?>
  <?php if (!$errors): ?>
  <p style="margin-top:1.5rem">✅ Done! <a href="/Charj/public/index.php/vehicles">View EVs →</a> &nbsp; <a href="/Charj/public/index.php/explore">Explore Brands →</a></p>
  <?php endif; ?>
</div>
</body>
</html>
