<?= $this->extend('layouts/public') ?>
<?= $this->section('content') ?>

<div class="min-h-screen bg-slate-50">
  <div class="max-w-3xl mx-auto px-4 pt-28 pb-20">
    <div class="bg-white rounded-3xl shadow-sm border border-slate-100 p-8 sm:p-12">
      <h1 class="text-3xl font-black text-slate-900 mb-2">Disclaimer</h1>
      <p class="text-sm text-slate-400 mb-8">Last updated: June 2025</p>

      <div class="space-y-6 text-sm text-slate-700 leading-relaxed">
        <div class="bg-amber-50 border border-amber-200 rounded-2xl p-5">
          <p class="font-bold text-amber-900">Charj.in is an independent EV information platform. We are not affiliated with any EV manufacturer, dealer, or government body.</p>
        </div>
        <section>
          <h2 class="text-lg font-black text-slate-900 mb-2">Price Information</h2>
          <p>All prices on Charj.in are ex-showroom prices sourced from manufacturers and are indicative only. On-road prices vary by state, RTO charges, insurance, and dealer handling fees. Always confirm the final price with your local dealer.</p>
        </section>
        <section>
          <h2 class="text-lg font-black text-slate-900 mb-2">Range & Performance</h2>
          <p>Claimed range figures are provided by manufacturers under standardised test conditions. Real-world range varies based on riding style, road conditions, payload, temperature, and AC usage. Typically expect 70–85% of claimed range.</p>
        </section>
        <section>
          <h2 class="text-lg font-black text-slate-900 mb-2">Subsidy & FAME II Information</h2>
          <p>Government subsidy information (FAME II, state subsidies) may change without notice. Always verify current subsidy amounts with the dealer or the relevant state transport authority before purchase.</p>
        </section>
        <section>
          <h2 class="text-lg font-black text-slate-900 mb-2">AI Recommendations</h2>
          <p>EV recommendations generated by our AI tool are based on the preferences you input and our vehicle database. They are suggestions only — not professional advice. Always test drive and do your own research before buying.</p>
        </section>
        <section>
          <h2 class="text-lg font-black text-slate-900 mb-2">Charging Station Data</h2>
          <p>Charging station information is sourced from OpenChargeMap and may not reflect the current operational status of stations. Always confirm charger availability before planning a trip.</p>
        </section>
      </div>

      <div class="mt-10 pt-6 border-t border-slate-100 flex gap-3">
        <a href="<?= base_url() ?>" class="btn-primary text-sm !py-2.5 !px-5">← Back to Home</a>
        <a href="<?= base_url('contact') ?>" class="btn-outline text-sm !py-2.5 !px-5">Contact Us</a>
      </div>
    </div>
  </div>
</div>

<?= $this->endSection() ?>
